### ISSUE TITLE
Extension should be enabled by default

### ISSUE THREAD

**Issue by xvkdev** [XirvikMadrid/xirvik_chrome_plugin#3]
Some users report that 2.4 doesn't work. At least a couple of them have the problem that the checkbox "Enable extension" is disabled by default. 

I just checked and it seems to happen when an existing extension (2.3) is updated; however new installations are OK.

**Comment by Novik** [comment]
I hope, I fix this.
I wasn't change plugins version ( current one is 2.5 with a fixed deluge functionality )

**Comment by xvkdev** [comment]
Uploaded to the Chrome store as 2.51 (I changed the manifest manually) - it
didn't allow me to upload a different file for 2.5 which I had already
uploaded some minutes ago.
