### ISSUE TITLE
Sorting directory list

### ISSUE THREAD

**Issue by xvkdev** [XirvikMadrid/xirvik_chrome_plugin#6]
I'm using ruTorrent and have "directory selection" set to "at runtime". Before, it used to be sorted ascending alphabetically. However, recently it changed to being sorted in descending alphabetical order. Is there a setting somewhere to set it back to ascending?

[user question]

**Comment by Novik** [comment]
Fixed for both versions of plugin.
Plugins version is unchanged.

**Comment by xvkdev** [comment]
Version number must always change, otherwise I cannot upload to the app
stores, they reject duplicate versions.

**Comment by Novik** [comment]
>  Version number must always change, 

I have not information - is you already uploaded version with a previous fix or not.
But on your wish.

**Comment by xvkdev** [comment]
Yes, I uploaded them yesterday. I try to upload the plugins every day if
there's a new version.
