### ISSUE TITLE
Add import / export functionality

### ISSUE THREAD

**Issue by Novik** [XirvikMadrid/xirvik_chrome_plugin#8]
i would like to thank you for providing your Add-On(s) "Xirvik .torrent to seedbox uploader" which can be found for

1) Firefox: https://addons.mozilla.org/de/firefox/addon/xirvik-torrent-to-seedbox-uplo/
2) Chrome: https://chrome.google.com/webstore/detail/xirvik-torrent-to-seedbox/gljdkkichjgocpdmiaachhlfccddcjgb?hl=de
because they are indeed very useful.

I would like to suggest to upgrade these Add-Ons with a very important feature, which would be very helpful in case i want to set up my Workstation-PC from scratch, and that is an option to export (and import) the current settings/saved servers.

Unfortunately as it is right now, this can't be done and i use up to 8 seedboxes from several providers, which makes setting them up manually an unnecessary hassle.

I thank you for considering

**Comment by Novik** [comment]
Correct this please:

"The connection used to load resources from https://promos.xirvik.com used TLS 1.0 or TLS 1.1, which are deprecated and will be disabled in the future. Once disabled, users will be prevented from loading these resources. The server should enable TLS 1.2 or later. See https://www.chromestatus.com/feature/5654791610957824 for more information."

**Comment by xvkdev** [comment]
We need to get rid for that promos shit. I want to do promos and actually you did some work on it ages ago that hasn't been used yet. Maybe now it would be a good time, since Black Friday is coming.

promos.xirvik.com is running Debian 6 and was apparently installed in 2012. 

Let's put its out of its misery by removing any link to it.

**Comment by Novik** [comment]
https://github.com/XirvikMadrid/xirvik_chrome_plugin/issues/9

**Comment by Novik** [comment]
As result we will have two additional buttons in the options, "Import" and "Export".
When user press 'export', then we show to him standard window prompt with selected json string. User must copy this string and use it in the 'import' feature in the future.
When user press 'import', them we show to him standard window prompt, user enter saved string and, if all correct we will replace all servers and options.

I need a correct english description for these prompts.
In these descriptions we must to describe functionality and pay users attention to the two features:
1) Result string may contain users passwords in the plain text on the export 
2) All existing servers will be wiped during import.

**Comment by xvkdev** [comment]
> As result we will have two additional buttons in the options, "Import" and "Export".
> When user press 'export', then we show to him standard window prompt with selected json string. User must copy this string and use it in the 'import' feature in the future.

Is it possible that the json file is just downloaded (and later uploaded)? That would be better, but if the plugin interface doesn't allow it then copy/pasting will work I guess.

> When user press 'import', them we show to him standard window prompt, user enter saved string and, if all correct we will replace all servers and options.

OK, so assuming it's a copy / pasted JSON I'd say:

"Export" => Display a text that says
"In the next screen you will have a JSON string with your existing configuration.  Keep in mind that this string contains everything including user names and password (visible). Make a copy of it in a safe place to use it in the future to restore the configuration."

[ OK ] [ Cancel ]

Import =>"Paste the configuration JSON string in the textbox below."

( ) Append the configuration to my existing one
( ) Overwrite the existing configuration 

[ OK ] [ Cancel ]

**Comment by Novik** [comment]
> Is it possible that the json file is just downloaded (and later uploaded)?

At this moment I don't know how to do this.

> OK, so assuming it's a copy / pasted JSON I'd say:

Done (for firefox extension too).
Current version changed to 3.10.
