### ISSUE TITLE
We need to get rid for that promos shit.

### ISSUE THREAD

**Issue by Novik** [XirvikMadrid/xirvik_chrome_plugin#9]
We need to get rid for that promos shit. I want to do promos and actually you did some work on it ages ago that hasn't been used yet. Maybe now it would be a good time, since Black Friday is coming.

promos.xirvik.com is running Debian 6 and was apparently installed in 2012.

Let's put its out of its misery by removing any link to it.

**Comment by Novik** [comment]
Removed (from firefox addon too)

**Comment by xvkdev** [comment]
Chrome plugin uploaded to Chrome store (currently pending review).
